#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define EVENT_OBJ_GFX_BRENDAN_NORMAL               0
#define EVENT_OBJ_GFX_BRENDAN_MACH_BIKE            1
#define EVENT_OBJ_GFX_BRENDAN_SURFING              2
#define EVENT_OBJ_GFX_BRENDAN_FIELD_MOVE           3
#define EVENT_OBJ_GFX_QUINTY_PLUMP                 4
#define EVENT_OBJ_GFX_NINJA_BOY                    5
#define EVENT_OBJ_GFX_TWIN                         6
#define EVENT_OBJ_GFX_BOY_1                        7
#define EVENT_OBJ_GFX_GIRL_1                       8
#define EVENT_OBJ_GFX_BOY_2                        9
#define EVENT_OBJ_GFX_GIRL_2                      10
#define EVENT_OBJ_GFX_LITTLE_BOY                  11
#define EVENT_OBJ_GFX_LITTLE_GIRL                 12
#define EVENT_OBJ_GFX_BOY_3                       13
#define EVENT_OBJ_GFX_GIRL_3                      14
#define EVENT_OBJ_GFX_RICH_BOY                    15
#define EVENT_OBJ_GFX_WOMAN_1                     16
#define EVENT_OBJ_GFX_FAT_MAN                     17
#define EVENT_OBJ_GFX_POKEFAN_F                   18
#define EVENT_OBJ_GFX_MAN_1                       19
#define EVENT_OBJ_GFX_WOMAN_2                     20
#define EVENT_OBJ_GFX_EXPERT_M                    21
#define EVENT_OBJ_GFX_EXPERT_F                    22
#define EVENT_OBJ_GFX_MAN_2                       23
#define EVENT_OBJ_GFX_WOMAN_3                     24
#define EVENT_OBJ_GFX_POKEFAN_M                   25
#define EVENT_OBJ_GFX_WOMAN_4                     26
#define EVENT_OBJ_GFX_COOK                        27
#define EVENT_OBJ_GFX_LINK_RECEPTIONIST           28
#define EVENT_OBJ_GFX_OLD_MAN                     29
#define EVENT_OBJ_GFX_OLD_WOMAN                   30
#define EVENT_OBJ_GFX_CAMPER                      31
#define EVENT_OBJ_GFX_PICNICKER                   32
#define EVENT_OBJ_GFX_MAN_3                       33
#define EVENT_OBJ_GFX_WOMAN_5                     34
#define EVENT_OBJ_GFX_YOUNGSTER                   35
#define EVENT_OBJ_GFX_BUG_CATCHER                 36
#define EVENT_OBJ_GFX_PSYCHIC_M                   37
#define EVENT_OBJ_GFX_SCHOOL_KID_M                38
#define EVENT_OBJ_GFX_MANIAC                      39
#define EVENT_OBJ_GFX_HEX_MANIAC                  40
#define EVENT_OBJ_GFX_RAYQUAZA_1                  41
#define EVENT_OBJ_GFX_SWIMMER_M                   42
#define EVENT_OBJ_GFX_SWIMMER_F                   43
#define EVENT_OBJ_GFX_BLACK_BELT                  44
#define EVENT_OBJ_GFX_BEAUTY                      45
#define EVENT_OBJ_GFX_SCIENTIST_1                 46
#define EVENT_OBJ_GFX_LASS                        47
#define EVENT_OBJ_GFX_GENTLEMAN                   48
#define EVENT_OBJ_GFX_SAILOR                      49
#define EVENT_OBJ_GFX_FISHERMAN                   50
#define EVENT_OBJ_GFX_RUNNING_TRIATHLETE_M        51
#define EVENT_OBJ_GFX_RUNNING_TRIATHLETE_F        52
#define EVENT_OBJ_GFX_TUBER_F                     53
#define EVENT_OBJ_GFX_TUBER_M                     54
#define EVENT_OBJ_GFX_HIKER                       55
#define EVENT_OBJ_GFX_CYCLING_TRIATHLETE_M        56
#define EVENT_OBJ_GFX_CYCLING_TRIATHLETE_F        57
#define EVENT_OBJ_GFX_NURSE                       58
#define EVENT_OBJ_GFX_ITEM_BALL                   59
#define EVENT_OBJ_GFX_BERRY_TREE                  60
#define EVENT_OBJ_GFX_BERRY_TREE_EARLY_STAGES     61
#define EVENT_OBJ_GFX_BERRY_TREE_LATE_STAGES      62
#define EVENT_OBJ_GFX_BRENDAN_ACRO_BIKE           63
#define EVENT_OBJ_GFX_PROF_BIRCH                  64
#define EVENT_OBJ_GFX_MAN_4                       65
#define EVENT_OBJ_GFX_MAN_5                       66
#define EVENT_OBJ_GFX_REPORTER_M                  67
#define EVENT_OBJ_GFX_REPORTER_F                  68
#define EVENT_OBJ_GFX_BARD                        69
#define EVENT_OBJ_GFX_ANABEL                      70
#define EVENT_OBJ_GFX_TUCKER                      71
#define EVENT_OBJ_GFX_GRETA                       72
#define EVENT_OBJ_GFX_SPENSER                     73
#define EVENT_OBJ_GFX_NOLAND                      74
#define EVENT_OBJ_GFX_LUCY                        75
#define EVENT_OBJ_GFX_UNUSED_NATU_DOLL            76
#define EVENT_OBJ_GFX_UNUSED_MAGNEMITE_DOLL       77
#define EVENT_OBJ_GFX_UNUSED_SQUIRTLE_DOLL        78
#define EVENT_OBJ_GFX_UNUSED_WOOPER_DOLL          79
#define EVENT_OBJ_GFX_UNUSED_PIKACHU_DOLL         80
#define EVENT_OBJ_GFX_UNUSED_PORYGON2_DOLL        81
#define EVENT_OBJ_GFX_CUTTABLE_TREE               82
#define EVENT_OBJ_GFX_MART_EMPLOYEE               83
#define EVENT_OBJ_GFX_ROOFTOP_SALE_WOMAN          84
#define EVENT_OBJ_GFX_TEALA                       85
#define EVENT_OBJ_GFX_BREAKABLE_ROCK              86
#define EVENT_OBJ_GFX_PUSHABLE_BOULDER            87
#define EVENT_OBJ_GFX_MR_BRINEYS_BOAT             88
#define EVENT_OBJ_GFX_MAY_NORMAL                  89
#define EVENT_OBJ_GFX_MAY_MACH_BIKE               90
#define EVENT_OBJ_GFX_MAY_ACRO_BIKE               91
#define EVENT_OBJ_GFX_MAY_SURFING                 92
#define EVENT_OBJ_GFX_MAY_FIELD_MOVE              93
#define EVENT_OBJ_GFX_TRUCK                       94
#define EVENT_OBJ_GFX_VIGOROTH_CARRYING_BOX       95
#define EVENT_OBJ_GFX_VIGOROTH_FACING_AWAY        96
#define EVENT_OBJ_GFX_BIRCHS_BAG                  97
#define EVENT_OBJ_GFX_ZIGZAGOON_1                 98
#define EVENT_OBJ_GFX_ARTIST                      99
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_NORMAL       100
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_SURFING      103
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define EVENT_OBJ_GFX_RIVAL_MAY_NORMAL           105
#define EVENT_OBJ_GFX_RIVAL_MAY_MACH_BIKE        106
#define EVENT_OBJ_GFX_RIVAL_MAY_ACRO_BIKE        107
#define EVENT_OBJ_GFX_RIVAL_MAY_SURFING          108
#define EVENT_OBJ_GFX_RIVAL_MAY_FIELD_MOVE       109
#define EVENT_OBJ_GFX_CAMERAMAN                  110
#define EVENT_OBJ_GFX_BRENDAN_UNDERWATER         111
#define EVENT_OBJ_GFX_MAY_UNDERWATER             112
#define EVENT_OBJ_GFX_MOVING_BOX                 113
#define EVENT_OBJ_GFX_CABLE_CAR                  114
#define EVENT_OBJ_GFX_SCIENTIST_2                115
#define EVENT_OBJ_GFX_DEVON_EMPLOYEE             116
#define EVENT_OBJ_GFX_AQUA_MEMBER_M              117
#define EVENT_OBJ_GFX_AQUA_MEMBER_F              118
#define EVENT_OBJ_GFX_MAGMA_MEMBER_M             119
#define EVENT_OBJ_GFX_MAGMA_MEMBER_F             120
#define EVENT_OBJ_GFX_SIDNEY                     121
#define EVENT_OBJ_GFX_PHOEBE                     122
#define EVENT_OBJ_GFX_GLACIA                     123
#define EVENT_OBJ_GFX_DRAKE                      124
#define EVENT_OBJ_GFX_ROXANNE                    125
#define EVENT_OBJ_GFX_BRAWLY                     126
#define EVENT_OBJ_GFX_WATTSON                    127
#define EVENT_OBJ_GFX_FLANNERY                   128
#define EVENT_OBJ_GFX_NORMAN                     129
#define EVENT_OBJ_GFX_WINONA                     130
#define EVENT_OBJ_GFX_LIZA                       131
#define EVENT_OBJ_GFX_TATE                       132
#define EVENT_OBJ_GFX_WALLACE                    133
#define EVENT_OBJ_GFX_STEVEN                     134
#define EVENT_OBJ_GFX_WALLY                      135
#define EVENT_OBJ_GFX_LITTLE_BOY_3               136
#define EVENT_OBJ_GFX_BRENDAN_FISHING            137
#define EVENT_OBJ_GFX_MAY_FISHING                138
#define EVENT_OBJ_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define EVENT_OBJ_GFX_SS_TIDAL                   140
#define EVENT_OBJ_GFX_SUBMARINE_SHADOW           141
#define EVENT_OBJ_GFX_PICHU_DOLL                 142
#define EVENT_OBJ_GFX_PIKACHU_DOLL               143
#define EVENT_OBJ_GFX_MARILL_DOLL                144
#define EVENT_OBJ_GFX_TOGEPI_DOLL                145
#define EVENT_OBJ_GFX_CYNDAQUIL_DOLL             146
#define EVENT_OBJ_GFX_CHIKORITA_DOLL             147
#define EVENT_OBJ_GFX_TOTODILE_DOLL              148
#define EVENT_OBJ_GFX_JIGGLYPUFF_DOLL            149
#define EVENT_OBJ_GFX_MEOWTH_DOLL                150
#define EVENT_OBJ_GFX_CLEFAIRY_DOLL              151
#define EVENT_OBJ_GFX_DITTO_DOLL                 152
#define EVENT_OBJ_GFX_SMOOCHUM_DOLL              153
#define EVENT_OBJ_GFX_TREECKO_DOLL               154
#define EVENT_OBJ_GFX_TORCHIC_DOLL               155
#define EVENT_OBJ_GFX_MUDKIP_DOLL                156
#define EVENT_OBJ_GFX_DUSKULL_DOLL               157
#define EVENT_OBJ_GFX_WYNAUT_DOLL                158
#define EVENT_OBJ_GFX_BALTOY_DOLL                159
#define EVENT_OBJ_GFX_KECLEON_DOLL               160
#define EVENT_OBJ_GFX_AZURILL_DOLL               161
#define EVENT_OBJ_GFX_SKITTY_DOLL                162
#define EVENT_OBJ_GFX_SWABLU_DOLL                163
#define EVENT_OBJ_GFX_GULPIN_DOLL                164
#define EVENT_OBJ_GFX_LOTAD_DOLL                 165
#define EVENT_OBJ_GFX_SEEDOT_DOLL                166
#define EVENT_OBJ_GFX_PIKA_CUSHION               167
#define EVENT_OBJ_GFX_ROUND_CUSHION              168
#define EVENT_OBJ_GFX_KISS_CUSHION               169
#define EVENT_OBJ_GFX_ZIGZAG_CUSHION             170
#define EVENT_OBJ_GFX_SPIN_CUSHION               171
#define EVENT_OBJ_GFX_DIAMOND_CUSHION            172
#define EVENT_OBJ_GFX_BALL_CUSHION               173
#define EVENT_OBJ_GFX_GRASS_CUSHION              174
#define EVENT_OBJ_GFX_FIRE_CUSHION               175
#define EVENT_OBJ_GFX_WATER_CUSHION              176
#define EVENT_OBJ_GFX_BIG_SNORLAX_DOLL           177
#define EVENT_OBJ_GFX_BIG_RHYDON_DOLL            178
#define EVENT_OBJ_GFX_BIG_LAPRAS_DOLL            179
#define EVENT_OBJ_GFX_BIG_VENUSAUR_DOLL          180
#define EVENT_OBJ_GFX_BIG_CHARIZARD_DOLL         181
#define EVENT_OBJ_GFX_BIG_BLASTOISE_DOLL         182
#define EVENT_OBJ_GFX_BIG_WAILMER_DOLL           183
#define EVENT_OBJ_GFX_BIG_REGIROCK_DOLL          184
#define EVENT_OBJ_GFX_BIG_REGICE_DOLL            185
#define EVENT_OBJ_GFX_BIG_REGISTEEL_DOLL         186
#define EVENT_OBJ_GFX_LATIAS                     187
#define EVENT_OBJ_GFX_LATIOS                     188
#define EVENT_OBJ_GFX_GAMEBOY_KID                189
#define EVENT_OBJ_GFX_CONTEST_JUDGE              190
#define EVENT_OBJ_GFX_BRENDAN_WATERING           191
#define EVENT_OBJ_GFX_MAY_WATERING               192
#define EVENT_OBJ_GFX_BRENDAN_DECORATING         193
#define EVENT_OBJ_GFX_MAY_DECORATING             194
#define EVENT_OBJ_GFX_ARCHIE                     195
#define EVENT_OBJ_GFX_MAXIE                      196
#define EVENT_OBJ_GFX_KYOGRE_1                   197
#define EVENT_OBJ_GFX_GROUDON_1                  198
#define EVENT_OBJ_GFX_FOSSIL                     199
#define EVENT_OBJ_GFX_REGIROCK                   200
#define EVENT_OBJ_GFX_REGICE                     201
#define EVENT_OBJ_GFX_REGISTEEL                  202
#define EVENT_OBJ_GFX_SKITTY                     203
#define EVENT_OBJ_GFX_KECLEON_1                  204
#define EVENT_OBJ_GFX_KYOGRE_2                   205
#define EVENT_OBJ_GFX_GROUDON_2                  206
#define EVENT_OBJ_GFX_RAYQUAZA_2                 207
#define EVENT_OBJ_GFX_ZIGZAGOON_2                208
#define EVENT_OBJ_GFX_PIKACHU                    209
#define EVENT_OBJ_GFX_AZUMARILL                  210
#define EVENT_OBJ_GFX_WINGULL                    211
#define EVENT_OBJ_GFX_KECLEON_2                  212
#define EVENT_OBJ_GFX_TUBER_M_SWIMMING           213
#define EVENT_OBJ_GFX_AZURILL                    214
#define EVENT_OBJ_GFX_MOM                        215
#define EVENT_OBJ_GFX_LINK_BRENDAN               216
#define EVENT_OBJ_GFX_LINK_MAY                   217
#define EVENT_OBJ_GFX_JUAN                       218
#define EVENT_OBJ_GFX_SCOTT                      219
#define EVENT_OBJ_GFX_POOCHYENA                  220
#define EVENT_OBJ_GFX_KYOGRE_3                   221
#define EVENT_OBJ_GFX_GROUDON_3                  222
#define EVENT_OBJ_GFX_MYSTERY_GIFT_MAN           223
#define EVENT_OBJ_GFX_TRICK_HOUSE_STATUE         224
#define EVENT_OBJ_GFX_KIRLIA                     225
#define EVENT_OBJ_GFX_DUSCLOPS                   226
#define EVENT_OBJ_GFX_UNION_ROOM_NURSE           227
#define EVENT_OBJ_GFX_SUDOWOODO                  228
#define EVENT_OBJ_GFX_MEW                        229
#define EVENT_OBJ_GFX_RED                        230
#define EVENT_OBJ_GFX_LEAF                       231
#define EVENT_OBJ_GFX_DEOXYS                     232
#define EVENT_OBJ_GFX_DEOXYS_TRIANGLE            233
#define EVENT_OBJ_GFX_BRANDON                    234
#define EVENT_OBJ_GFX_LINK_RS_BRENDAN            235
#define EVENT_OBJ_GFX_LINK_RS_MAY                236
#define EVENT_OBJ_GFX_LUGIA                      237
#define EVENT_OBJ_GFX_HOOH                       238
#define EVENT_OBJ_GFX_PKMN_1                       239  //SWSB宝可梦行走图
#define EVENT_OBJ_GFX_PKMN_2                       240
#define EVENT_OBJ_GFX_PKMN_3                       241
#define EVENT_OBJ_GFX_PKMN_4                       242
#define EVENT_OBJ_GFX_PKMN_5                       243
#define EVENT_OBJ_GFX_PKMN_6                       244
#define EVENT_OBJ_GFX_PKMN_7                       245
#define EVENT_OBJ_GFX_PKMN_8                       246
#define EVENT_OBJ_GFX_PKMN_9                       247
#define EVENT_OBJ_GFX_PKMN_10                       248
#define EVENT_OBJ_GFX_PKMN_11                       249
#define EVENT_OBJ_GFX_PKMN_12                       250
#define EVENT_OBJ_GFX_PKMN_13                       251
#define EVENT_OBJ_GFX_PKMN_14                       252
#define EVENT_OBJ_GFX_PKMN_15                       253
#define EVENT_OBJ_GFX_PKMN_16                       254
#define EVENT_OBJ_GFX_PKMN_17                       255
#define EVENT_OBJ_GFX_PKMN_18                       256
#define EVENT_OBJ_GFX_PKMN_19                       257
#define EVENT_OBJ_GFX_PKMN_20                       258
#define EVENT_OBJ_GFX_PKMN_21                       259
#define EVENT_OBJ_GFX_PKMN_22                       260
#define EVENT_OBJ_GFX_PKMN_23                       261
#define EVENT_OBJ_GFX_PKMN_24                       262
#define EVENT_OBJ_GFX_PKMN_25                       263
#define EVENT_OBJ_GFX_PKMN_26                       264
#define EVENT_OBJ_GFX_PKMN_27                       265
#define EVENT_OBJ_GFX_PKMN_28                       266
#define EVENT_OBJ_GFX_PKMN_29                       267
#define EVENT_OBJ_GFX_PKMN_30                       268
#define EVENT_OBJ_GFX_PKMN_31                       269
#define EVENT_OBJ_GFX_PKMN_32                       270
#define EVENT_OBJ_GFX_PKMN_33                       271
#define EVENT_OBJ_GFX_PKMN_34                       272
#define EVENT_OBJ_GFX_PKMN_35                       273
#define EVENT_OBJ_GFX_PKMN_36                       274
#define EVENT_OBJ_GFX_PKMN_37                       275
#define EVENT_OBJ_GFX_PKMN_38                       276
#define EVENT_OBJ_GFX_PKMN_39                       277
#define EVENT_OBJ_GFX_PKMN_40                       278
#define EVENT_OBJ_GFX_PKMN_41                       279
#define EVENT_OBJ_GFX_PKMN_42                       280
#define EVENT_OBJ_GFX_PKMN_43                       281
#define EVENT_OBJ_GFX_PKMN_44                       282
#define EVENT_OBJ_GFX_PKMN_45                       283
#define EVENT_OBJ_GFX_PKMN_46                       284
#define EVENT_OBJ_GFX_PKMN_47                       285
#define EVENT_OBJ_GFX_PKMN_48                       286
#define EVENT_OBJ_GFX_PKMN_49                       287
#define EVENT_OBJ_GFX_PKMN_50                       288
#define EVENT_OBJ_GFX_PKMN_51                       289
#define EVENT_OBJ_GFX_PKMN_52                       290
#define EVENT_OBJ_GFX_PKMN_53                       291
#define EVENT_OBJ_GFX_PKMN_54                       292
#define EVENT_OBJ_GFX_PKMN_55                       293
#define EVENT_OBJ_GFX_PKMN_56                       294
#define EVENT_OBJ_GFX_PKMN_57                       295
#define EVENT_OBJ_GFX_PKMN_58                       296
#define EVENT_OBJ_GFX_PKMN_59                       297
#define EVENT_OBJ_GFX_PKMN_60                       298
#define EVENT_OBJ_GFX_PKMN_61                       299
#define EVENT_OBJ_GFX_PKMN_62                       300
#define EVENT_OBJ_GFX_PKMN_63                       301
#define EVENT_OBJ_GFX_PKMN_64                       302
#define EVENT_OBJ_GFX_PKMN_65                       303
#define EVENT_OBJ_GFX_PKMN_66                       304
#define EVENT_OBJ_GFX_PKMN_67                       305
#define EVENT_OBJ_GFX_PKMN_68                       306
#define EVENT_OBJ_GFX_PKMN_69                       307
#define EVENT_OBJ_GFX_PKMN_70                       308
#define EVENT_OBJ_GFX_PKMN_71                       309
#define EVENT_OBJ_GFX_PKMN_72                       310
#define EVENT_OBJ_GFX_PKMN_73                       311
#define EVENT_OBJ_GFX_PKMN_74                       312
#define EVENT_OBJ_GFX_PKMN_75                       313
#define EVENT_OBJ_GFX_PKMN_76                       314
#define EVENT_OBJ_GFX_PKMN_77                       315
#define EVENT_OBJ_GFX_PKMN_78                       316
#define EVENT_OBJ_GFX_PKMN_79                       317
#define EVENT_OBJ_GFX_PKMN_80                       318
#define EVENT_OBJ_GFX_PKMN_81                       319
#define EVENT_OBJ_GFX_PKMN_82                       320
#define EVENT_OBJ_GFX_PKMN_83                       321
#define EVENT_OBJ_GFX_PKMN_84                       322
#define EVENT_OBJ_GFX_PKMN_85                       323
#define EVENT_OBJ_GFX_PKMN_86                       324
#define EVENT_OBJ_GFX_PKMN_87                       325
#define EVENT_OBJ_GFX_PKMN_88                       326
#define EVENT_OBJ_GFX_PKMN_89                       327
#define EVENT_OBJ_GFX_PKMN_90                       328
#define EVENT_OBJ_GFX_PKMN_91                       329
#define EVENT_OBJ_GFX_PKMN_92                       330
#define EVENT_OBJ_GFX_PKMN_93                       331
#define EVENT_OBJ_GFX_PKMN_94                       332
#define EVENT_OBJ_GFX_PKMN_95                       333
#define EVENT_OBJ_GFX_PKMN_96                       334
#define EVENT_OBJ_GFX_PKMN_97                       335
#define EVENT_OBJ_GFX_PKMN_98                       336
#define EVENT_OBJ_GFX_PKMN_99                       337
#define EVENT_OBJ_GFX_PKMN_100                       338
#define EVENT_OBJ_GFX_PKMN_101                       339
#define EVENT_OBJ_GFX_PKMN_102                       340
#define EVENT_OBJ_GFX_PKMN_103                       341
#define EVENT_OBJ_GFX_PKMN_104                       342
#define EVENT_OBJ_GFX_PKMN_105                       343
#define EVENT_OBJ_GFX_PKMN_106                       344
#define EVENT_OBJ_GFX_PKMN_107                       345
#define EVENT_OBJ_GFX_PKMN_108                       346
#define EVENT_OBJ_GFX_PKMN_109                       347
#define EVENT_OBJ_GFX_PKMN_110                       348
#define EVENT_OBJ_GFX_PKMN_111                       349
#define EVENT_OBJ_GFX_PKMN_112                       350
#define EVENT_OBJ_GFX_PKMN_113                       351
#define EVENT_OBJ_GFX_PKMN_114                       352
#define EVENT_OBJ_GFX_PKMN_115                       353
#define EVENT_OBJ_GFX_PKMN_116                       354
#define EVENT_OBJ_GFX_PKMN_117                       355
#define EVENT_OBJ_GFX_PKMN_118                       356
#define EVENT_OBJ_GFX_PKMN_119                       357
#define EVENT_OBJ_GFX_PKMN_120                       358
#define EVENT_OBJ_GFX_PKMN_121                       359
#define EVENT_OBJ_GFX_PKMN_122                       360
#define EVENT_OBJ_GFX_PKMN_123                       361
#define EVENT_OBJ_GFX_PKMN_124                       362
#define EVENT_OBJ_GFX_PKMN_125                       363
#define EVENT_OBJ_GFX_PKMN_126                       364
#define EVENT_OBJ_GFX_PKMN_127                       365
#define EVENT_OBJ_GFX_PKMN_128                       366
#define EVENT_OBJ_GFX_PKMN_129                       367
#define EVENT_OBJ_GFX_PKMN_130                       368
#define EVENT_OBJ_GFX_PKMN_131                       369
#define EVENT_OBJ_GFX_PKMN_132                       370
#define EVENT_OBJ_GFX_PKMN_133                       371
#define EVENT_OBJ_GFX_PKMN_134                       372
#define EVENT_OBJ_GFX_PKMN_135                       373
#define EVENT_OBJ_GFX_PKMN_136                       374
#define EVENT_OBJ_GFX_PKMN_137                       375
#define EVENT_OBJ_GFX_PKMN_138                       376
#define EVENT_OBJ_GFX_PKMN_139                       377
#define EVENT_OBJ_GFX_PKMN_140                       378
#define EVENT_OBJ_GFX_PKMN_141                       379
#define EVENT_OBJ_GFX_PKMN_142                       380
#define EVENT_OBJ_GFX_PKMN_143                       381
#define EVENT_OBJ_GFX_PKMN_144                       382
#define EVENT_OBJ_GFX_PKMN_145                       383
#define EVENT_OBJ_GFX_PKMN_146                       384
#define EVENT_OBJ_GFX_PKMN_147                       385
#define EVENT_OBJ_GFX_PKMN_148                       386
#define EVENT_OBJ_GFX_PKMN_149                       387
#define EVENT_OBJ_GFX_PKMN_150                       388
#define EVENT_OBJ_GFX_PKMN_151                       389
#define EVENT_OBJ_GFX_PKMN_152                       390
#define EVENT_OBJ_GFX_PKMN_153                       391
#define EVENT_OBJ_GFX_PKMN_154                       392
#define EVENT_OBJ_GFX_PKMN_155                       393
#define EVENT_OBJ_GFX_PKMN_156                       394
#define EVENT_OBJ_GFX_PKMN_157                       395
#define EVENT_OBJ_GFX_PKMN_158                       396
#define EVENT_OBJ_GFX_PKMN_159                       397
#define EVENT_OBJ_GFX_PKMN_160                       398
#define EVENT_OBJ_GFX_PKMN_161                       399
#define EVENT_OBJ_GFX_PKMN_162                       400
#define EVENT_OBJ_GFX_PKMN_163                       401
#define EVENT_OBJ_GFX_PKMN_164                       402
#define EVENT_OBJ_GFX_PKMN_165                       403
#define EVENT_OBJ_GFX_PKMN_166                       404
#define EVENT_OBJ_GFX_PKMN_167                       405
#define EVENT_OBJ_GFX_PKMN_168                       406
#define EVENT_OBJ_GFX_PKMN_169                       407
#define EVENT_OBJ_GFX_PKMN_170                       408
#define EVENT_OBJ_GFX_PKMN_171                       409
#define EVENT_OBJ_GFX_PKMN_172                       410
#define EVENT_OBJ_GFX_PKMN_173                       411
#define EVENT_OBJ_GFX_PKMN_174                       412
#define EVENT_OBJ_GFX_PKMN_175                       413
#define EVENT_OBJ_GFX_PKMN_176                       414
#define EVENT_OBJ_GFX_PKMN_177                       415
#define EVENT_OBJ_GFX_PKMN_178                       416
#define EVENT_OBJ_GFX_PKMN_179                       417
#define EVENT_OBJ_GFX_PKMN_180                       418
#define EVENT_OBJ_GFX_PKMN_181                       419
#define EVENT_OBJ_GFX_PKMN_182                       420
#define EVENT_OBJ_GFX_PKMN_183                       421
#define EVENT_OBJ_GFX_PKMN_184                       422
#define EVENT_OBJ_GFX_PKMN_185                       423
#define EVENT_OBJ_GFX_PKMN_186                       424
#define EVENT_OBJ_GFX_PKMN_187                       425
#define EVENT_OBJ_GFX_PKMN_188                       426
#define EVENT_OBJ_GFX_PKMN_189                       427
#define EVENT_OBJ_GFX_PKMN_190                       428
#define EVENT_OBJ_GFX_PKMN_191                       429
#define EVENT_OBJ_GFX_PKMN_192                       430
#define EVENT_OBJ_GFX_PKMN_193                       431
#define EVENT_OBJ_GFX_PKMN_194                       432
#define EVENT_OBJ_GFX_PKMN_195                       433
#define EVENT_OBJ_GFX_PKMN_196                       434
#define EVENT_OBJ_GFX_PKMN_197                       435
#define EVENT_OBJ_GFX_PKMN_198                       436
#define EVENT_OBJ_GFX_PKMN_199                       437
#define EVENT_OBJ_GFX_PKMN_200                       438
#define EVENT_OBJ_GFX_PKMN_201                       439
#define EVENT_OBJ_GFX_PKMN_202                       440
#define EVENT_OBJ_GFX_PKMN_203                       441
#define EVENT_OBJ_GFX_PKMN_204                       442
#define EVENT_OBJ_GFX_PKMN_205                       443
#define EVENT_OBJ_GFX_PKMN_206                       444
#define EVENT_OBJ_GFX_PKMN_207                       445
#define EVENT_OBJ_GFX_PKMN_208                       446
#define EVENT_OBJ_GFX_PKMN_209                       447
#define EVENT_OBJ_GFX_PKMN_210                       448
#define EVENT_OBJ_GFX_PKMN_211                       449
#define EVENT_OBJ_GFX_PKMN_212                       450
#define EVENT_OBJ_GFX_PKMN_213                       451
#define EVENT_OBJ_GFX_PKMN_214                       452
#define EVENT_OBJ_GFX_PKMN_215                       453
#define EVENT_OBJ_GFX_PKMN_216                       454
#define EVENT_OBJ_GFX_PKMN_217                       455
#define EVENT_OBJ_GFX_PKMN_218                       456
#define EVENT_OBJ_GFX_PKMN_219                       457
#define EVENT_OBJ_GFX_PKMN_220                       458
#define EVENT_OBJ_GFX_PKMN_221                       459
#define EVENT_OBJ_GFX_PKMN_222                       460
#define EVENT_OBJ_GFX_PKMN_223                       461
#define EVENT_OBJ_GFX_PKMN_224                       462
#define EVENT_OBJ_GFX_PKMN_225                       463
#define EVENT_OBJ_GFX_PKMN_226                       464
#define EVENT_OBJ_GFX_PKMN_227                       465
#define EVENT_OBJ_GFX_PKMN_228                       466
#define EVENT_OBJ_GFX_PKMN_229                       467
#define EVENT_OBJ_GFX_PKMN_230                       468
#define EVENT_OBJ_GFX_PKMN_231                       469
#define EVENT_OBJ_GFX_PKMN_232                       470
#define EVENT_OBJ_GFX_PKMN_233                       471
#define EVENT_OBJ_GFX_PKMN_234                       472
#define EVENT_OBJ_GFX_PKMN_235                       473
#define EVENT_OBJ_GFX_PKMN_236                       474
#define EVENT_OBJ_GFX_PKMN_237                       475
#define EVENT_OBJ_GFX_PKMN_238                       476
#define EVENT_OBJ_GFX_PKMN_239                       477
#define EVENT_OBJ_GFX_PKMN_240                       478
#define EVENT_OBJ_GFX_PKMN_241                       479
#define EVENT_OBJ_GFX_PKMN_242                       480
#define EVENT_OBJ_GFX_PKMN_243                       481
#define EVENT_OBJ_GFX_PKMN_244                       482
#define EVENT_OBJ_GFX_PKMN_245                       483
#define EVENT_OBJ_GFX_PKMN_246                       484
#define EVENT_OBJ_GFX_PKMN_247                       485
#define EVENT_OBJ_GFX_PKMN_248                       486
#define EVENT_OBJ_GFX_PKMN_249                       487
#define EVENT_OBJ_GFX_PKMN_250                       488
#define EVENT_OBJ_GFX_PKMN_251                       489
#define EVENT_OBJ_GFX_PKMN_252                       490
#define EVENT_OBJ_GFX_PKMN_253                       491
#define EVENT_OBJ_GFX_PKMN_254                       492
#define EVENT_OBJ_GFX_PKMN_255                       493
#define EVENT_OBJ_GFX_PKMN_256                       494
#define EVENT_OBJ_GFX_PKMN_257                       495
#define EVENT_OBJ_GFX_PKMN_258                       496
#define EVENT_OBJ_GFX_PKMN_259                       497
#define EVENT_OBJ_GFX_PKMN_260                       498
#define EVENT_OBJ_GFX_PKMN_261                       499
#define EVENT_OBJ_GFX_PKMN_262                       500
#define EVENT_OBJ_GFX_PKMN_263                       501
#define EVENT_OBJ_GFX_PKMN_264                       502
#define EVENT_OBJ_GFX_PKMN_265                       503
#define EVENT_OBJ_GFX_PKMN_266                       504
#define EVENT_OBJ_GFX_PKMN_267                       505
#define EVENT_OBJ_GFX_PKMN_268                       506
#define EVENT_OBJ_GFX_PKMN_269                       507
#define EVENT_OBJ_GFX_PKMN_270                       508
#define EVENT_OBJ_GFX_PKMN_271                       509
#define EVENT_OBJ_GFX_PKMN_272                       510
#define EVENT_OBJ_GFX_PKMN_273                       511
#define EVENT_OBJ_GFX_PKMN_274                       512
#define EVENT_OBJ_GFX_PKMN_275                       513
#define EVENT_OBJ_GFX_PKMN_276                       514
#define EVENT_OBJ_GFX_PKMN_277                       515
#define EVENT_OBJ_GFX_PKMN_278                       516
#define EVENT_OBJ_GFX_PKMN_279                       517
#define EVENT_OBJ_GFX_PKMN_280                       518
#define EVENT_OBJ_GFX_PKMN_281                       519
#define EVENT_OBJ_GFX_PKMN_282                       520
#define EVENT_OBJ_GFX_PKMN_283                       521
#define EVENT_OBJ_GFX_PKMN_284                       522
#define EVENT_OBJ_GFX_PKMN_285                       523
#define EVENT_OBJ_GFX_PKMN_286                       524
#define EVENT_OBJ_GFX_PKMN_287                       525
#define EVENT_OBJ_GFX_PKMN_288                       526
#define EVENT_OBJ_GFX_PKMN_289                       527
#define EVENT_OBJ_GFX_PKMN_290                       528
#define EVENT_OBJ_GFX_PKMN_291                       529
#define EVENT_OBJ_GFX_PKMN_292                       530
#define EVENT_OBJ_GFX_PKMN_293                       531
#define EVENT_OBJ_GFX_PKMN_294                       532
#define EVENT_OBJ_GFX_PKMN_295                       533
#define EVENT_OBJ_GFX_PKMN_296                       534
#define EVENT_OBJ_GFX_PKMN_297                       535
#define EVENT_OBJ_GFX_PKMN_298                       536
#define EVENT_OBJ_GFX_PKMN_299                       537
#define EVENT_OBJ_GFX_PKMN_300                       538
#define EVENT_OBJ_GFX_PKMN_301                       539
#define EVENT_OBJ_GFX_PKMN_302                       540
#define EVENT_OBJ_GFX_PKMN_303                       541
#define EVENT_OBJ_GFX_PKMN_304                       542
#define EVENT_OBJ_GFX_PKMN_305                       543
#define EVENT_OBJ_GFX_PKMN_306                       544
#define EVENT_OBJ_GFX_PKMN_307                       545
#define EVENT_OBJ_GFX_PKMN_308                       546
#define EVENT_OBJ_GFX_PKMN_309                       547
#define EVENT_OBJ_GFX_PKMN_310                       548
#define EVENT_OBJ_GFX_PKMN_311                       549
#define EVENT_OBJ_GFX_PKMN_312                       550
#define EVENT_OBJ_GFX_PKMN_313                       551
#define EVENT_OBJ_GFX_PKMN_314                       552
#define EVENT_OBJ_GFX_PKMN_315                       553
#define EVENT_OBJ_GFX_PKMN_316                       554
#define EVENT_OBJ_GFX_PKMN_317                       555
#define EVENT_OBJ_GFX_PKMN_318                       556
#define EVENT_OBJ_GFX_PKMN_319                       557
#define EVENT_OBJ_GFX_PKMN_320                       558
#define EVENT_OBJ_GFX_PKMN_321                       559
#define EVENT_OBJ_GFX_PKMN_322                       560
#define EVENT_OBJ_GFX_PKMN_323                       561
#define EVENT_OBJ_GFX_PKMN_324                       562
#define EVENT_OBJ_GFX_PKMN_325                       563
#define EVENT_OBJ_GFX_PKMN_326                       564
#define EVENT_OBJ_GFX_PKMN_327                       565
#define EVENT_OBJ_GFX_PKMN_328                       566
#define EVENT_OBJ_GFX_PKMN_329                       567
#define EVENT_OBJ_GFX_PKMN_330                       568
#define EVENT_OBJ_GFX_PKMN_331                       569
#define EVENT_OBJ_GFX_PKMN_332                       570
#define EVENT_OBJ_GFX_PKMN_333                       571
#define EVENT_OBJ_GFX_PKMN_334                       572
#define EVENT_OBJ_GFX_PKMN_335                       573
#define EVENT_OBJ_GFX_PKMN_336                       574
#define EVENT_OBJ_GFX_PKMN_337                       575
#define EVENT_OBJ_GFX_PKMN_338                       576
#define EVENT_OBJ_GFX_PKMN_339                       577
#define EVENT_OBJ_GFX_PKMN_340                       578
#define EVENT_OBJ_GFX_PKMN_341                       579
#define EVENT_OBJ_GFX_PKMN_342                       580
#define EVENT_OBJ_GFX_PKMN_343                       581
#define EVENT_OBJ_GFX_PKMN_344                       582
#define EVENT_OBJ_GFX_PKMN_345                       583
#define EVENT_OBJ_GFX_PKMN_346                       584
#define EVENT_OBJ_GFX_PKMN_347                       585
#define EVENT_OBJ_GFX_PKMN_348                       586
#define EVENT_OBJ_GFX_PKMN_349                       587
#define EVENT_OBJ_GFX_PKMN_350                       588
#define EVENT_OBJ_GFX_PKMN_351                       589
#define EVENT_OBJ_GFX_PKMN_352                       590
#define EVENT_OBJ_GFX_PKMN_353                       591
#define EVENT_OBJ_GFX_PKMN_354                       592
#define EVENT_OBJ_GFX_PKMN_355                       593
#define EVENT_OBJ_GFX_PKMN_356                       594
#define EVENT_OBJ_GFX_PKMN_357                       595
#define EVENT_OBJ_GFX_PKMN_358                       596
#define EVENT_OBJ_GFX_PKMN_359                       597
#define EVENT_OBJ_GFX_PKMN_360                       598
#define EVENT_OBJ_GFX_PKMN_361                       599
#define EVENT_OBJ_GFX_PKMN_362                       600
#define EVENT_OBJ_GFX_PKMN_363                       601
#define EVENT_OBJ_GFX_PKMN_364                       602
#define EVENT_OBJ_GFX_PKMN_365                       603
#define EVENT_OBJ_GFX_PKMN_366                       604
#define EVENT_OBJ_GFX_PKMN_367                       605
#define EVENT_OBJ_GFX_PKMN_368                       606
#define EVENT_OBJ_GFX_PKMN_369                       607
#define EVENT_OBJ_GFX_PKMN_370                       608
#define EVENT_OBJ_GFX_PKMN_371                       609
#define EVENT_OBJ_GFX_PKMN_372                       610
#define EVENT_OBJ_GFX_PKMN_373                       611
#define EVENT_OBJ_GFX_PKMN_374                       612
#define EVENT_OBJ_GFX_PKMN_375                       613
#define EVENT_OBJ_GFX_PKMN_376                       614
#define EVENT_OBJ_GFX_PKMN_377                       615
#define EVENT_OBJ_GFX_PKMN_378                       616
#define EVENT_OBJ_GFX_PKMN_379                       617
#define EVENT_OBJ_GFX_PKMN_380                       618
#define EVENT_OBJ_GFX_PKMN_381                       619
#define EVENT_OBJ_GFX_PKMN_382                       620
#define EVENT_OBJ_GFX_PKMN_383                       621
#define EVENT_OBJ_GFX_PKMN_384                       622
#define EVENT_OBJ_GFX_PKMN_385                       623
#define EVENT_OBJ_GFX_PKMN_386                       624
#define EVENT_OBJ_GFX_PKMN_387                       625
#define EVENT_OBJ_GFX_PKMN_388                       626
#define EVENT_OBJ_GFX_PKMN_389                       627
#define EVENT_OBJ_GFX_PKMN_390                       628
#define EVENT_OBJ_GFX_PKMN_391                       629
#define EVENT_OBJ_GFX_PKMN_392                       630
#define EVENT_OBJ_GFX_PKMN_393                       631
#define EVENT_OBJ_GFX_PKMN_394                       632
#define EVENT_OBJ_GFX_PKMN_395                       633
#define EVENT_OBJ_GFX_PKMN_396                       634
#define EVENT_OBJ_GFX_PKMN_397                       635
#define EVENT_OBJ_GFX_PKMN_398                       636
#define EVENT_OBJ_GFX_PKMN_399                       637
#define EVENT_OBJ_GFX_PKMN_400                       638
#define EVENT_OBJ_GFX_PKMN_401                       639
#define EVENT_OBJ_GFX_PKMN_402                       640
#define EVENT_OBJ_GFX_PKMN_403                       641
#define EVENT_OBJ_GFX_PKMN_404                       642
#define EVENT_OBJ_GFX_PKMN_405                       643
#define EVENT_OBJ_GFX_PKMN_406                       644
#define EVENT_OBJ_GFX_PKMN_407                       645
#define EVENT_OBJ_GFX_PKMN_408                       646
#define EVENT_OBJ_GFX_PKMN_409                       647
#define EVENT_OBJ_GFX_PKMN_410                       648
#define EVENT_OBJ_GFX_PKMN_411                       649
#define EVENT_OBJ_GFX_PKMN_412                       650
#define EVENT_OBJ_GFX_PKMN_413                       651
#define EVENT_OBJ_GFX_PKMN_414                       652
#define EVENT_OBJ_GFX_PKMN_415                       653
#define EVENT_OBJ_GFX_PKMN_416                       654
#define EVENT_OBJ_GFX_PKMN_417                       655
#define EVENT_OBJ_GFX_PKMN_418                       656
#define EVENT_OBJ_GFX_PKMN_419                       657
#define EVENT_OBJ_GFX_PKMN_420                       658
#define EVENT_OBJ_GFX_PKMN_421                       659
#define EVENT_OBJ_GFX_PKMN_422                       660
#define EVENT_OBJ_GFX_PKMN_423                       661
#define EVENT_OBJ_GFX_PKMN_424                       662
#define EVENT_OBJ_GFX_PKMN_425                       663
#define EVENT_OBJ_GFX_PKMN_426                       664
#define EVENT_OBJ_GFX_PKMN_427                       665
#define EVENT_OBJ_GFX_PKMN_428                       666
#define EVENT_OBJ_GFX_PKMN_429                       667
#define EVENT_OBJ_GFX_PKMN_430                       668
#define EVENT_OBJ_GFX_PKMN_431                       669
#define EVENT_OBJ_GFX_PKMN_432                       670
#define EVENT_OBJ_GFX_PKMN_433                       671
#define EVENT_OBJ_GFX_PKMN_434                       672
#define EVENT_OBJ_GFX_PKMN_435                       673
#define EVENT_OBJ_GFX_PKMN_436                       674
#define EVENT_OBJ_GFX_PKMN_437                       675
#define EVENT_OBJ_GFX_PKMN_438                       676
#define EVENT_OBJ_GFX_PKMN_439                       677
#define EVENT_OBJ_GFX_PKMN_440                       678
#define EVENT_OBJ_GFX_PKMN_441                       679
#define EVENT_OBJ_GFX_PKMN_442                       680
#define EVENT_OBJ_GFX_PKMN_443                       681
#define EVENT_OBJ_GFX_PKMN_444                       682
#define EVENT_OBJ_GFX_PKMN_445                       683
#define EVENT_OBJ_GFX_PKMN_446                       684
#define EVENT_OBJ_GFX_PKMN_447                       685
#define EVENT_OBJ_GFX_PKMN_448                       686
#define EVENT_OBJ_GFX_PKMN_449                       687
#define EVENT_OBJ_GFX_PKMN_450                       688
#define EVENT_OBJ_GFX_PKMN_451                       689
#define EVENT_OBJ_GFX_PKMN_452                       690
#define EVENT_OBJ_GFX_PKMN_453                       691
#define EVENT_OBJ_GFX_PKMN_454                       692
#define EVENT_OBJ_GFX_PKMN_455                       693
#define EVENT_OBJ_GFX_PKMN_456                       694
#define EVENT_OBJ_GFX_PKMN_457                       695
#define EVENT_OBJ_GFX_PKMN_458                       696
#define EVENT_OBJ_GFX_PKMN_459                       697
#define EVENT_OBJ_GFX_PKMN_460                       698
#define EVENT_OBJ_GFX_PKMN_461                       699
#define EVENT_OBJ_GFX_PKMN_462                       700
#define EVENT_OBJ_GFX_PKMN_463                       701
#define EVENT_OBJ_GFX_PKMN_464                       702
#define EVENT_OBJ_GFX_PKMN_465                       703
#define EVENT_OBJ_GFX_PKMN_466                       704
#define EVENT_OBJ_GFX_PKMN_467                       705
#define EVENT_OBJ_GFX_PKMN_468                       706
#define EVENT_OBJ_GFX_PKMN_469                       707
#define EVENT_OBJ_GFX_PKMN_470                       708
#define EVENT_OBJ_GFX_PKMN_471                       709
#define EVENT_OBJ_GFX_PKMN_472                       710
#define EVENT_OBJ_GFX_PKMN_473                       711
#define EVENT_OBJ_GFX_PKMN_474                       712
#define EVENT_OBJ_GFX_PKMN_475                       713
#define EVENT_OBJ_GFX_PKMN_476                       714
#define EVENT_OBJ_GFX_PKMN_477                       715
#define EVENT_OBJ_GFX_PKMN_478                       716
#define EVENT_OBJ_GFX_PKMN_479                       717
#define EVENT_OBJ_GFX_PKMN_480                       718
#define EVENT_OBJ_GFX_PKMN_481                       719
#define EVENT_OBJ_GFX_PKMN_482                       720
#define EVENT_OBJ_GFX_PKMN_483                       721
#define EVENT_OBJ_GFX_PKMN_484                       722
#define EVENT_OBJ_GFX_PKMN_485                       723
#define EVENT_OBJ_GFX_PKMN_486                       724
#define EVENT_OBJ_GFX_PKMN_487                       725
#define EVENT_OBJ_GFX_PKMN_488                       726
#define EVENT_OBJ_GFX_PKMN_489                       727
#define EVENT_OBJ_GFX_PKMN_490                       728
#define EVENT_OBJ_GFX_PKMN_491                       729
#define EVENT_OBJ_GFX_PKMN_492                       730
#define EVENT_OBJ_GFX_PKMN_493                       731
#define EVENT_OBJ_GFX_PKMN_494                       732
#define EVENT_OBJ_GFX_PKMN_495                       733
#define EVENT_OBJ_GFX_PKMN_496                       734
#define EVENT_OBJ_GFX_PKMN_497                       735
#define EVENT_OBJ_GFX_PKMN_498                       736
#define EVENT_OBJ_GFX_PKMN_499                       737
#define EVENT_OBJ_GFX_PKMN_500                       738
#define EVENT_OBJ_GFX_PKMN_501                       739
#define EVENT_OBJ_GFX_PKMN_502                       740
#define EVENT_OBJ_GFX_PKMN_503                       741
#define EVENT_OBJ_GFX_PKMN_504                       742
#define EVENT_OBJ_GFX_PKMN_505                       743
#define EVENT_OBJ_GFX_PKMN_506                       744
#define EVENT_OBJ_GFX_PKMN_507                       745
#define EVENT_OBJ_GFX_PKMN_508                       746
#define EVENT_OBJ_GFX_PKMN_509                       747
#define EVENT_OBJ_GFX_PKMN_510                       748
#define EVENT_OBJ_GFX_PKMN_511                       749
#define EVENT_OBJ_GFX_PKMN_512                       750
#define EVENT_OBJ_GFX_PKMN_513                       751
#define EVENT_OBJ_GFX_PKMN_514                       752
#define EVENT_OBJ_GFX_PKMN_515                       753
#define EVENT_OBJ_GFX_PKMN_516                       754
#define EVENT_OBJ_GFX_PKMN_517                       755
#define EVENT_OBJ_GFX_PKMN_518                       756
#define EVENT_OBJ_GFX_PKMN_519                       757
#define EVENT_OBJ_GFX_PKMN_520                       758
#define EVENT_OBJ_GFX_PKMN_521                       759
#define EVENT_OBJ_GFX_PKMN_522                       760
#define EVENT_OBJ_GFX_PKMN_523                       761
#define EVENT_OBJ_GFX_PKMN_524                       762
#define EVENT_OBJ_GFX_PKMN_525                       763
#define EVENT_OBJ_GFX_PKMN_526                       764
#define EVENT_OBJ_GFX_PKMN_527                       765
#define EVENT_OBJ_GFX_PKMN_528                       766
#define EVENT_OBJ_GFX_PKMN_529                       767
#define EVENT_OBJ_GFX_PKMN_530                       768
#define EVENT_OBJ_GFX_PKMN_531                       769
#define EVENT_OBJ_GFX_PKMN_532                       770
#define EVENT_OBJ_GFX_PKMN_533                       771
#define EVENT_OBJ_GFX_PKMN_534                       772
#define EVENT_OBJ_GFX_PKMN_535                       773
#define EVENT_OBJ_GFX_PKMN_536                       774
#define EVENT_OBJ_GFX_PKMN_537                       775
#define EVENT_OBJ_GFX_PKMN_538                       776
#define EVENT_OBJ_GFX_PKMN_539                       777
#define EVENT_OBJ_GFX_PKMN_540                       778
#define EVENT_OBJ_GFX_PKMN_541                       779
#define EVENT_OBJ_GFX_PKMN_542                       780
#define EVENT_OBJ_GFX_PKMN_543                       781
#define EVENT_OBJ_GFX_PKMN_544                       782
#define EVENT_OBJ_GFX_PKMN_545                       783
#define EVENT_OBJ_GFX_PKMN_546                       784
#define EVENT_OBJ_GFX_PKMN_547                       785
#define EVENT_OBJ_GFX_PKMN_548                       786
#define EVENT_OBJ_GFX_PKMN_549                       787
#define EVENT_OBJ_GFX_PKMN_550                       788
#define EVENT_OBJ_GFX_PKMN_551                       789
#define EVENT_OBJ_GFX_PKMN_552                       790
#define EVENT_OBJ_GFX_PKMN_553                       791
#define EVENT_OBJ_GFX_PKMN_554                       792
#define EVENT_OBJ_GFX_PKMN_555                       793
#define EVENT_OBJ_GFX_PKMN_556                       794
#define EVENT_OBJ_GFX_PKMN_557                       795
#define EVENT_OBJ_GFX_PKMN_558                       796
#define EVENT_OBJ_GFX_PKMN_559                       797
#define EVENT_OBJ_GFX_PKMN_560                       798
#define EVENT_OBJ_GFX_PKMN_561                       799
#define EVENT_OBJ_GFX_PKMN_562                       800
#define EVENT_OBJ_GFX_PKMN_563                       801
#define EVENT_OBJ_GFX_PKMN_564                       802
#define EVENT_OBJ_GFX_PKMN_565                       803
#define EVENT_OBJ_GFX_PKMN_566                       804
#define EVENT_OBJ_GFX_PKMN_567                       805
#define EVENT_OBJ_GFX_PKMN_568                       806
#define EVENT_OBJ_GFX_PKMN_569                       807
#define EVENT_OBJ_GFX_PKMN_570                       808
#define EVENT_OBJ_GFX_PKMN_571                       809
#define EVENT_OBJ_GFX_PKMN_572                       810
#define EVENT_OBJ_GFX_PKMN_573                       811
#define EVENT_OBJ_GFX_PKMN_574                       812
#define EVENT_OBJ_GFX_PKMN_575                       813
#define EVENT_OBJ_GFX_PKMN_576                       814
#define EVENT_OBJ_GFX_PKMN_577                       815
#define EVENT_OBJ_GFX_PKMN_578                       816
#define EVENT_OBJ_GFX_PKMN_579                       817
#define EVENT_OBJ_GFX_PKMN_580                       818
#define EVENT_OBJ_GFX_PKMN_581                       819
#define EVENT_OBJ_GFX_PKMN_582                       820
#define EVENT_OBJ_GFX_PKMN_583                       821
#define EVENT_OBJ_GFX_PKMN_584                       822
#define EVENT_OBJ_GFX_PKMN_585                       823
#define EVENT_OBJ_GFX_PKMN_586                       824
#define EVENT_OBJ_GFX_PKMN_587                       825
#define EVENT_OBJ_GFX_PKMN_588                       826
#define EVENT_OBJ_GFX_PKMN_589                       827
#define EVENT_OBJ_GFX_PKMN_590                       828
#define EVENT_OBJ_GFX_PKMN_591                       829
#define EVENT_OBJ_GFX_PKMN_592                       830
#define EVENT_OBJ_GFX_PKMN_593                       831
#define EVENT_OBJ_GFX_PKMN_594                       832
#define EVENT_OBJ_GFX_PKMN_595                       833
#define EVENT_OBJ_GFX_PKMN_596                       834
#define EVENT_OBJ_GFX_PKMN_597                       835
#define EVENT_OBJ_GFX_PKMN_598                       836
#define EVENT_OBJ_GFX_PKMN_599                       837
#define EVENT_OBJ_GFX_PKMN_600                       838
#define EVENT_OBJ_GFX_PKMN_601                       839
#define EVENT_OBJ_GFX_PKMN_602                       840
#define EVENT_OBJ_GFX_PKMN_603                       841
#define EVENT_OBJ_GFX_PKMN_604                       842
#define EVENT_OBJ_GFX_PKMN_605                       843
#define EVENT_OBJ_GFX_PKMN_606                       844
#define EVENT_OBJ_GFX_PKMN_607                       845
#define EVENT_OBJ_GFX_PKMN_608                       846
#define EVENT_OBJ_GFX_PKMN_609                       847
#define EVENT_OBJ_GFX_PKMN_610                       848
#define EVENT_OBJ_GFX_PKMN_611                       849
#define EVENT_OBJ_GFX_PKMN_612                       850
#define EVENT_OBJ_GFX_PKMN_613                       851
#define EVENT_OBJ_GFX_PKMN_614                       852
#define EVENT_OBJ_GFX_PKMN_615                       853
#define EVENT_OBJ_GFX_PKMN_616                       854
#define EVENT_OBJ_GFX_PKMN_617                       855
#define EVENT_OBJ_GFX_PKMN_618                       856
#define EVENT_OBJ_GFX_PKMN_619                       857
#define EVENT_OBJ_GFX_PKMN_620                       858
#define EVENT_OBJ_GFX_PKMN_621                       859
#define EVENT_OBJ_GFX_PKMN_622                       860
#define EVENT_OBJ_GFX_PKMN_623                       861
#define EVENT_OBJ_GFX_PKMN_624                       862
#define EVENT_OBJ_GFX_PKMN_625                       863
#define EVENT_OBJ_GFX_PKMN_626                       864
#define EVENT_OBJ_GFX_PKMN_627                       865
#define EVENT_OBJ_GFX_PKMN_628                       866
#define EVENT_OBJ_GFX_PKMN_629                       867
#define EVENT_OBJ_GFX_PKMN_630                       868
#define EVENT_OBJ_GFX_PKMN_631                       869
#define EVENT_OBJ_GFX_PKMN_632                       870
#define EVENT_OBJ_GFX_PKMN_633                       871
#define EVENT_OBJ_GFX_PKMN_634                       872
#define EVENT_OBJ_GFX_PKMN_635                       873
#define EVENT_OBJ_GFX_PKMN_636                       874
#define EVENT_OBJ_GFX_PKMN_637                       875
#define EVENT_OBJ_GFX_PKMN_638                       876
#define EVENT_OBJ_GFX_PKMN_639                       877
#define EVENT_OBJ_GFX_PKMN_640                       878
#define EVENT_OBJ_GFX_PKMN_641                       879
#define EVENT_OBJ_GFX_PKMN_642                       880
#define EVENT_OBJ_GFX_PKMN_643                       881
#define EVENT_OBJ_GFX_PKMN_644                       882
#define EVENT_OBJ_GFX_PKMN_645                       883
#define EVENT_OBJ_GFX_PKMN_646                       884
#define EVENT_OBJ_GFX_PKMN_647                       885
#define EVENT_OBJ_GFX_PKMN_648                       886
#define EVENT_OBJ_GFX_PKMN_649                       887
#define EVENT_OBJ_GFX_PKMN_650                       888
#define EVENT_OBJ_GFX_PKMN_651                       889
#define EVENT_OBJ_GFX_PKMN_652                       890
#define EVENT_OBJ_GFX_PKMN_653                       891
#define EVENT_OBJ_GFX_PKMN_654                       892
#define EVENT_OBJ_GFX_PKMN_655                       893
#define EVENT_OBJ_GFX_PKMN_656                       894
#define EVENT_OBJ_GFX_PKMN_657                       895
#define EVENT_OBJ_GFX_PKMN_658                       896
#define EVENT_OBJ_GFX_PKMN_659                       897
#define EVENT_OBJ_GFX_PKMN_660                       898
#define EVENT_OBJ_GFX_PKMN_661                       899
#define EVENT_OBJ_GFX_PKMN_662                       900
#define EVENT_OBJ_GFX_PKMN_663                       901
#define EVENT_OBJ_GFX_PKMN_664                       902
#define EVENT_OBJ_GFX_PKMN_665                       903
#define EVENT_OBJ_GFX_PKMN_666                       904
#define EVENT_OBJ_GFX_PKMN_667                       905
#define EVENT_OBJ_GFX_PKMN_668                       906
#define EVENT_OBJ_GFX_PKMN_669                       907
#define EVENT_OBJ_GFX_PKMN_670                       908
#define EVENT_OBJ_GFX_PKMN_671                       909
#define EVENT_OBJ_GFX_PKMN_672                       910
#define EVENT_OBJ_GFX_PKMN_673                       911
#define EVENT_OBJ_GFX_PKMN_674                       912
#define EVENT_OBJ_GFX_PKMN_675                       913
#define EVENT_OBJ_GFX_PKMN_676                       914
#define EVENT_OBJ_GFX_PKMN_677                       915
#define EVENT_OBJ_GFX_PKMN_678                       916
#define EVENT_OBJ_GFX_PKMN_679                       917
#define EVENT_OBJ_GFX_PKMN_680                       918
#define EVENT_OBJ_GFX_PKMN_681                       919
#define EVENT_OBJ_GFX_PKMN_682                       920
#define EVENT_OBJ_GFX_PKMN_683                       921
#define EVENT_OBJ_GFX_PKMN_684                       922
#define EVENT_OBJ_GFX_PKMN_685                       923
#define EVENT_OBJ_GFX_PKMN_686                       924
#define EVENT_OBJ_GFX_PKMN_687                       925
#define EVENT_OBJ_GFX_PKMN_688                       926
#define EVENT_OBJ_GFX_PKMN_689                       927
#define EVENT_OBJ_GFX_PKMN_690                       928
#define EVENT_OBJ_GFX_PKMN_691                       929
#define EVENT_OBJ_GFX_PKMN_692                       930
#define EVENT_OBJ_GFX_PKMN_693                       931
#define EVENT_OBJ_GFX_PKMN_694                       932
#define EVENT_OBJ_GFX_PKMN_695                       933
#define EVENT_OBJ_GFX_PKMN_696                       934
#define EVENT_OBJ_GFX_PKMN_697                       935
#define EVENT_OBJ_GFX_PKMN_698                       936
#define EVENT_OBJ_GFX_PKMN_699                       937
#define EVENT_OBJ_GFX_PKMN_700                       938
#define EVENT_OBJ_GFX_PKMN_701                       939
#define EVENT_OBJ_GFX_PKMN_702                       940
#define EVENT_OBJ_GFX_PKMN_703                       941
#define EVENT_OBJ_GFX_PKMN_704                       942
#define EVENT_OBJ_GFX_PKMN_705                       943
#define EVENT_OBJ_GFX_PKMN_706                       944
#define EVENT_OBJ_GFX_PKMN_707                       945
#define EVENT_OBJ_GFX_PKMN_708                       946
#define EVENT_OBJ_GFX_PKMN_709                       947
#define EVENT_OBJ_GFX_PKMN_710                       948
#define EVENT_OBJ_GFX_PKMN_711                       949
#define EVENT_OBJ_GFX_PKMN_712                       950
#define EVENT_OBJ_GFX_PKMN_713                       951
#define EVENT_OBJ_GFX_PKMN_714                       952
#define EVENT_OBJ_GFX_PKMN_715                       953
#define EVENT_OBJ_GFX_PKMN_716                       954
#define EVENT_OBJ_GFX_PKMN_717                       955
#define EVENT_OBJ_GFX_PKMN_718                       956
#define EVENT_OBJ_GFX_PKMN_719                       957
#define EVENT_OBJ_GFX_PKMN_720                       958
#define EVENT_OBJ_GFX_PKMN_721                       959
#define EVENT_OBJ_GFX_PKMN_722                       960
#define EVENT_OBJ_GFX_PKMN_723                       961
#define EVENT_OBJ_GFX_PKMN_724                       962
#define EVENT_OBJ_GFX_PKMN_725                       963
#define EVENT_OBJ_GFX_PKMN_726                       964
#define EVENT_OBJ_GFX_PKMN_727                       965
#define EVENT_OBJ_GFX_PKMN_728                       966
#define EVENT_OBJ_GFX_PKMN_729                       967
#define EVENT_OBJ_GFX_PKMN_730                       968
#define EVENT_OBJ_GFX_PKMN_731                       969
#define EVENT_OBJ_GFX_PKMN_732                       970
#define EVENT_OBJ_GFX_PKMN_733                       971
#define EVENT_OBJ_GFX_PKMN_734                       972
#define EVENT_OBJ_GFX_PKMN_735                       973
#define EVENT_OBJ_GFX_PKMN_736                       974
#define EVENT_OBJ_GFX_PKMN_737                       975
#define EVENT_OBJ_GFX_PKMN_738                       976
#define EVENT_OBJ_GFX_PKMN_739                       977
#define EVENT_OBJ_GFX_PKMN_740                       978
#define EVENT_OBJ_GFX_PKMN_741                       979
#define EVENT_OBJ_GFX_PKMN_742                       980
#define EVENT_OBJ_GFX_PKMN_743                       981
#define EVENT_OBJ_GFX_PKMN_744                       982
#define EVENT_OBJ_GFX_PKMN_745                       983
#define EVENT_OBJ_GFX_PKMN_746                       984
#define EVENT_OBJ_GFX_PKMN_747                       985
#define EVENT_OBJ_GFX_PKMN_748                       986
#define EVENT_OBJ_GFX_PKMN_749                       987
#define EVENT_OBJ_GFX_PKMN_750                       988
#define EVENT_OBJ_GFX_PKMN_751                       989
#define EVENT_OBJ_GFX_PKMN_752                       990
#define EVENT_OBJ_GFX_PKMN_753                       991
#define EVENT_OBJ_GFX_PKMN_754                       992
#define EVENT_OBJ_GFX_PKMN_755                       993
#define EVENT_OBJ_GFX_PKMN_756                       994
#define EVENT_OBJ_GFX_PKMN_757                       995
#define EVENT_OBJ_GFX_PKMN_758                       996
#define EVENT_OBJ_GFX_PKMN_759                       997
#define EVENT_OBJ_GFX_PKMN_760                       998
#define EVENT_OBJ_GFX_PKMN_761                       999
#define EVENT_OBJ_GFX_PKMN_762                       1000
#define EVENT_OBJ_GFX_PKMN_763                       1001
#define EVENT_OBJ_GFX_PKMN_764                       1002
#define EVENT_OBJ_GFX_PKMN_765                       1003
#define EVENT_OBJ_GFX_PKMN_766                       1004
#define EVENT_OBJ_GFX_PKMN_767                       1005
#define EVENT_OBJ_GFX_PKMN_768                       1006
#define EVENT_OBJ_GFX_PKMN_769                       1007
#define EVENT_OBJ_GFX_PKMN_770                       1008
#define EVENT_OBJ_GFX_PKMN_771                       1009
#define EVENT_OBJ_GFX_PKMN_772                       1010
#define EVENT_OBJ_GFX_PKMN_773                       1011
#define EVENT_OBJ_GFX_PKMN_774                       1012
#define EVENT_OBJ_GFX_PKMN_775                       1013
#define EVENT_OBJ_GFX_PKMN_776                       1014
#define EVENT_OBJ_GFX_PKMN_777                       1015
#define EVENT_OBJ_GFX_PKMN_778                       1016
#define EVENT_OBJ_GFX_PKMN_779                       1017
#define EVENT_OBJ_GFX_PKMN_780                       1018
#define EVENT_OBJ_GFX_PKMN_781                       1019
#define EVENT_OBJ_GFX_PKMN_782                       1020
#define EVENT_OBJ_GFX_PKMN_783                       1021
#define EVENT_OBJ_GFX_PKMN_784                       1022
#define EVENT_OBJ_GFX_PKMN_785                       1023
#define EVENT_OBJ_GFX_PKMN_786                       1024
#define EVENT_OBJ_GFX_PKMN_787                       1025
#define EVENT_OBJ_GFX_PKMN_788                       1026
#define EVENT_OBJ_GFX_PKMN_789                       1027
#define EVENT_OBJ_GFX_PKMN_790                       1028
#define EVENT_OBJ_GFX_PKMN_791                       1029
#define EVENT_OBJ_GFX_PKMN_792                       1030
#define EVENT_OBJ_GFX_PKMN_793                       1031
#define EVENT_OBJ_GFX_PKMN_794                       1032
#define EVENT_OBJ_GFX_PKMN_795                       1033
#define EVENT_OBJ_GFX_PKMN_796                       1034
#define EVENT_OBJ_GFX_PKMN_797                       1035
#define EVENT_OBJ_GFX_PKMN_798                       1036
#define EVENT_OBJ_GFX_PKMN_799                       1037
#define EVENT_OBJ_GFX_PKMN_800                       1038
#define EVENT_OBJ_GFX_PKMN_801                       1039
#define EVENT_OBJ_GFX_PKMN_802                       1040
#define EVENT_OBJ_GFX_PKMN_803                       1041
#define EVENT_OBJ_GFX_PKMN_804                       1042
#define EVENT_OBJ_GFX_PKMN_805                       1043
#define EVENT_OBJ_GFX_PKMN_806                       1044
#define EVENT_OBJ_GFX_PKMN_807                       1045
#define EVENT_OBJ_GFX_BARD_2                     1046

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define EVENT_OBJ_GFX_VAR_0 1047
#define EVENT_OBJ_GFX_VAR_1 1048
#define EVENT_OBJ_GFX_VAR_2 1049
#define EVENT_OBJ_GFX_VAR_3 1050
#define EVENT_OBJ_GFX_VAR_4 1051
#define EVENT_OBJ_GFX_VAR_5 1052
#define EVENT_OBJ_GFX_VAR_6 1053
#define EVENT_OBJ_GFX_VAR_7 1054
#define EVENT_OBJ_GFX_VAR_8 1055
#define EVENT_OBJ_GFX_VAR_9 1056
#define EVENT_OBJ_GFX_VAR_A 1057
#define EVENT_OBJ_GFX_VAR_B 1058
#define EVENT_OBJ_GFX_VAR_C 1059
#define EVENT_OBJ_GFX_VAR_D 1060
#define EVENT_OBJ_GFX_VAR_E 1061
#define EVENT_OBJ_GFX_VAR_F 1062

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX EVENT_OBJ_GFX_PICHU_DOLL

#define EVENT_OBJ_ID_PLAYER 0xFF
#define EVENT_OBJ_ID_CAMERA 0x7F

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
