AtroposQuiteTown_MapScripts::
	.byte 0

AtroposQuiteTown_EventScript_1::
	msgbox AtroposQuiteTown_text1, MSGBOX_NPC
	end

AtroposQuiteTown_EventScript_2::
	msgbox AtroposQuiteTown_text2, MSGBOX_NPC
	end

AtroposQuiteTown_EventScript_3::
	msgbox AtroposQuiteTown_text3, MSGBOX_NPC
	end

AtroposQuiteTown_EventScript_4::
	msgbox AtroposQuiteTown_text4, MSGBOX_SIGN
	end

AtroposQuiteTown_EventScript_5::
	msgbox AtroposQuiteTown_text5, MSGBOX_SIGN
	end
	
AtroposQuiteTown_EventScript_6::
	msgbox AtroposQuiteTown_text6, MSGBOX_SIGN
	end
	
AtroposQuiteTown_EventScript_7::
	msgbox AtroposQuiteTown_text7, MSGBOX_SIGN
	end

AtroposQuiteTown_text1:
	.string "1$"

AtroposQuiteTown_text2:
	.string "2$"

AtroposQuiteTown_text3:
	.string "3$"

AtroposQuiteTown_text4:
	.string "4$"

AtroposQuiteTown_text5:
	.string "5$"

AtroposQuiteTown_text6:
	.string "6$"

AtroposQuiteTown_text7:
	.string "7$"

